title: "CSS苦手を克服！基礎から学ぶCSS講座"
summary: "最初の頃は`margin`や`padding`、`display:flex`が難しく、CSSに苦手意識を持つ方々が多くいるかと思います。
そんな苦手意識を払拭するような、誰かを補助できる本を目指して書いてみました。


内容は追加、更新していきます


学べること

・HTML、CSSの基礎（すこし）

・margin

・height

・padding

・margin

・border

・display:block、display:inline、display:inline-block

"


topics: ["html", "css", "プログラミング初心者"]
published: true
allow_override: true
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - 01-intro
  - 02-html_history
  - 03-css_history
  - 03-01-css_basic
  - 04-boxmodel
  - 04-01-boxmodel
  - 04-02-boxmodel
  - 04-03-boxmodel
  - 04-04-boxmodel
  - 04-05-boxmodel
  - 05-block


