title: "aws"
summary: "テーマはA4一枚で一つのサービスを説明する
なので1000文字以内に収める
コアサービスの解説
分厚い本は腐るほどある。
逆に短くまとまったものを提供する。
AWSの全体像を素早く知るための本
サービスを知るための本であり、GUIを使っての操作は含まれない

対象読者
* 急遽AWS触ってくださいと言われた方
* AWSの資格を勉強する方
"
topics: []
published: false
price: 0 # 有料の場合200〜5000
# 本に含めるチャプターを順番に並べましょう
chapters:
  - example1
  - example2

